### ISSUE TITLE
Error creating index

### ISSUE THREAD

**Issue by wcomichohg** [intel/sails-mssql#18]
Hi guys,

No errors installing the package. Set db account as owner of the test database.

I only have 1 model in my project and its the default user model of sails.js.

When I lift the project with the new connection,  I am getting the error below. Hope you could help on this:

Exception: `sendNativeQuery` failed ("queryFailed").  The database returned an error when attempting to execute the native query.
Additional data:

{
  error: RequestError: Could not create constraint or index. See previous errors.
      at handleError (C:\sails\test-project\node_modules\mssql\lib\tedious\request.js:366:15)
      at Connection.emit (events.js:210:5)
      at Connection.EventEmitter.emit (domain.js:475:20)
      at Parser.<anonymous> (C:\sails\test-project\node_modules\tedious\lib\connection.js:832:12)
      at Parser.emit (events.js:210:5)
      at Parser.EventEmitter.emit (domain.js:475:20)
      at Parser.<anonymous> (C:\sails\test-project\node_modules\tedious\lib\token\token-stream-parser.js:37:14)
      at Parser.emit (events.js:210:5)
      at Parser.EventEmitter.emit (domain.js:475:20)
      at addChunk (C:\sails\test-project\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:298:12)
      at readableAddChunk (C:\sails\test-project\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:280:11)
      at Parser.Readable.push (C:\sails\test-project\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:241:10)
      at Parser.Transform.push (C:\sails\test-project\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:139:32)
      at doneParsing (C:\sails\test-project\node_modules\tedious\lib\token\stream-parser.js:122:14)
      at C:\sails\test-project\node_modules\tedious\lib\token\infoerror-token-parser.js:48:5
      at C:\sails\test-project\node_modules\tedious\lib\token\infoerror-token-parser.js:21:19
      at C:\sails\test-project\node_modules\tedious\lib\token\stream-parser.js:221:7
      at Parser.awaitData (C:\sails\test-project\node_modules\tedious\lib\token\stream-parser.js:145:7)
      at Parser.readUInt32LE (C:\sails\test-project\node_modules\tedious\lib\token\stream-parser.js:218:10)
      at C:\sails\test-project\node_modules\tedious\lib\token\infoerror-token-parser.js:20:90
      at C:\sails\test-project\node_modules\tedious\lib\token\stream-parser.js:379:9
      at C:\sails\test-project\node_modules\tedious\lib\token\stream-parser.js:371:7
      at Parser.awaitData (C:\sails\test-project\node_modules\tedious\lib\token\stream-parser.js:145:7)
      at Parser.readBuffer (C:\sails\test-project\node_modules\tedious\lib\token\stream-parser.js:368:10)
      at C:\sails\test-project\node_modules\tedious\lib\token\stream-parser.js:378:12
      at C:\sails\test-project\node_modules\tedious\lib\token\stream-parser.js:165:7
      at Parser.awaitData (C:\sails\test-project\node_modules\tedious\lib\token\stream-parser.js:145:7)
      at Parser.readUInt8 (C:\sails\test-project\node_modules\tedious\lib\token\stream-parser.js:162:10)
      at Parser.readBVarChar (C:\sails\test-project\node_modules\tedious\lib\token\stream-parser.js:377:10)
      at C:\sails\test-project\node_modules\tedious\lib\token\infoerror-token-parser.js:19:22
      at C:\sails\test-project\node_modules\tedious\lib\token\stream-parser.js:379:9
      at C:\sails\test-project\node_modules\tedious\lib\token\stream-parser.js:371:7
      at Parser.awaitData (C:\sails\test-project\node_modules\tedious\lib\token\stream-parser.js:145:7)
      at Parser.readBuffer (C:\sails\test-project\node_modules\tedious\lib\token\stream-parser.js:368:10) {
    code: 'EREQUEST'

Thanks in advance

**Comment by wcomichohg** [comment]
Hi,

Got it. Removed the "unique" attribute of the email address. Sails created a unique ID column as index for the User model.
