### ISSUE TITLE
usingConnection error

### ISSUE THREAD

**Issue by kiapkiap** [intel/sails-mssql#41]
when i using (createEach or replaceCollection) and usingConnection together, it show up below error

{
  error: [RequestError: Requests can only be made in the LoggedIn state, not the LoggedIn state
    at Request.userCallback (C:\Users\user\Desktop\ecohaulsystem\icontrolsails\node_modules\mssql\lib\tedious\request.js:437:19)
    at Request.callback (C:\Users\user\Desktop\ecohaulsystem\icontrolsails\node_modules\tedious\lib\request.js:56:14)
    at Connection.makeRequest (C:\Users\user\Desktop\ecohaulsystem\icontrolsails\node_modules\tedious\lib\connection.js:1800:15)
    at Connection.execSql (C:\Users\user\Desktop\ecohaulsystem\icontrolsails\node_modules\tedious\lib\connection.js:1575:10)
    at C:\Users\user\Desktop\ecohaulsystem\icontrolsails\node_modules\mssql\lib\tedious\request.js:687:65
    at C:\Users\user\Desktop\ecohaulsystem\icontrolsails\node_modules\mssql\lib\base\connection-pool.js:100:41
  ] {
    code: 'EINVALIDSTATE',
    originalError: [RequestError: Requests can only be made in the LoggedIn state, not the LoggedIn state
      at RequestError (C:\Users\user\Desktop\ecohaulsystem\icontrolsails\node_modules\tedious\lib\errors.js:32:12)
      at Connection.makeRequest (C:\Users\user\Desktop\ecohaulsystem\icontrolsails\node_modules\tedious\lib\connection.js:1800:49)
      at Connection.execSql (C:\Users\user\Desktop\ecohaulsystem\icontrolsails\node_modules\tedious\lib\connection.js:1575:10)
      at C:\Users\user\Desktop\ecohaulsystem\icontrolsails\node_modules\mssql\lib\tedious\request.js:687:65
      at C:\Users\user\Desktop\ecohaulsystem\icontrolsails\node_modules\mssql\lib\base\connection-pool.js:100:41
    ] {
      code: 'EINVALIDSTATE'
    },
    number: 'EINVALIDSTATE',
    state: undefined,
    precedingErrors: []
  },
  meta: undefined
}

**Comment by kiapkiap** [comment]
sails/config/datastores.js
 default:{ url: 'db1' }
 
 code
 let Driver= sails.getDatastore().driver;
  var manager = (
      // await Driver.createManager({ connectionString: 'db2' })
      await Driver.createManager({ connectionString: defaultDatastore })
    ).manager;
    
   db2 = (
  await Driver.getConnection({ manager: manager })
).connection;
await Model.update(id).set(inputs).fetch().usingConnection(db2)

it will update to db2 but fetch back is db1
