### ISSUE TITLE
cannot load mssql adapter

### ISSUE THREAD

**Issue by koolfreak** [intel/sails-mssql#7]
Hi,
Latest SailsJS is having issues loading the adapter:

error: A hook (`orm`) failed to load!
error: Failed to lift app: { Error: There was an error attempting to load `sails-mssql`.
(Sails attempted to load this adapter because it is referenced by a datastore (`default`) in this app's configuration)
Please ensure that `sails-mssql` is a valid Sails/Waterline adapter, and that it is installed in this app.

Error details:
Error: Cannot find module 'machinepack-mssql'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

**Comment by koolfreak** [comment]
I already fix the issue.
